development:
  adapter: sqlite3
  host: localhost
  encoding: utf8
  database: BikeRental_dev
  pool: 5

test:
  adapter: sqlite3
  encoding: ut8
  database: BikeRental_test
  pool: 5

production:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: BikeRental_production
  pool: 5
